<?php
require __DIR__ . '/bootstrap/wordpress-stubs.php';
require __DIR__ . '/../includes/content/class-index-readiness-gate.php';
use TMWSEO\Engine\Content\IndexReadinessGate;
$GLOBALS['_tmw_test_posts']=[]; $GLOBALS['_tmw_test_post_meta']=[];
$tests=0;$fails=0;function ok($cond,$name,$detail=''){global $tests,$fails;$tests++; if($cond){echo "ok $name\n";}else{$fails++;echo "FAIL $name".($detail!==''?" — $detail":"")."\n";}}
function seed_ready_case($id,$content){$GLOBALS['_tmw_test_posts'][$id]=new WP_Post((object) ['ID'=>$id,'post_type'=>'tmw_category_page','post_content'=>$content]);update_post_meta($id,'_tmwseo_keyword','Primary Cam');update_post_meta($id,'_tmwseo_content_quality_score','90');update_post_meta($id,'_tmwseo_uniqueness_score','90');update_post_meta($id,'_tmwseo_keyword_confidence','90');update_post_meta($id,'_tmwseo_approval_status','approved');update_post_meta($id,'rank_math_focus_keyword','Primary Cam,active extra one, active extra two');}
seed_ready_case(1701,'');$r=IndexReadinessGate::evaluate_post(1701);ok(!$r['ready'],'empty content with active extras is not ready',json_encode($r));ok(in_array('active_chip_unused:active extra one:empty_content',$r['reasons'],true)&&in_array('active_chip_unused:active extra two:empty_content',$r['reasons'],true),'empty content reports stable active_chip_unused failures',json_encode($r['reasons']));
seed_ready_case(1702," \n\t  ");$r2=IndexReadinessGate::evaluate_post(1702);ok(!$r2['ready'],'whitespace-only content with active extras is not ready',json_encode($r2));ok(in_array('active_chip_unused:active extra one:empty_content',$r2['reasons'],true)&&in_array('active_chip_unused:active extra two:empty_content',$r2['reasons'],true),'whitespace-only content reports stable active_chip_unused failures',json_encode($r2['reasons']));

seed_ready_case(1704,'<p>&nbsp;</p>');$r4=IndexReadinessGate::evaluate_post(1704);ok(!$r4['ready'],'HTML NBSP paragraph with active extras is not ready',json_encode($r4));ok(in_array('active_chip_unused:active extra one:empty_content',$r4['reasons'],true)&&!empty($r4['gate_details']['visible_content_empty']),'HTML NBSP paragraph is normalized as empty visible content',json_encode($r4));
seed_ready_case(1705,'&#160;');$r5=IndexReadinessGate::evaluate_post(1705);ok(!$r5['ready'],'numeric NBSP entity with active extras is not ready',json_encode($r5));ok(in_array('active_chip_unused:active extra two:empty_content',$r5['reasons'],true)&&!empty($r5['gate_details']['visible_content_empty']),'numeric NBSP entity is normalized as empty visible content',json_encode($r5));
seed_ready_case(1706,"\u{00A0}");$r6=IndexReadinessGate::evaluate_post(1706);ok(!$r6['ready'],'Unicode NBSP with active extras is not ready',json_encode($r6));ok(in_array('active_chip_unused:active extra one:empty_content',$r6['reasons'],true)&&!empty($r6['gate_details']['visible_content_empty']),'Unicode NBSP is normalized as empty visible content',json_encode($r6));
seed_ready_case(1703,'<p>Real visible content with active extra one and active extra two.</p>');$r3=IndexReadinessGate::evaluate_post(1703);ok($r3['ready'],'non-empty content is not blocked by empty-content active-chip guard',json_encode($r3));ok(get_post_meta(1703,IndexReadinessGate::META_READY,true)==='1','readiness decision persists after non-empty readback');
echo "PASS ".($tests-$fails)." FAIL $fails\n"; exit($fails?1:0);
