'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path'); const { validateRequest } = require('../src/validate-request'); const { fetchProfile } = require('../src/fetch-profile');
const request = { provider: 'livejasmin', source_url: 'https://www.livejasmin.com/en/chat/AbbyMurray', username: 'AbbyMurray', request_id: 'test' };
const fixture = (name) => fs.readFileSync(path.join(__dirname, 'fixtures', name), 'utf8');
async function fixtureFetch(html, url = request.source_url) { const { chromium } = require('playwright'); return fetchProfile(request, { browserFactory: async () => ({ newContext: async () => { const browser = await chromium.launch({ headless: true }); const context = await browser.newContext(); const page = await context.newPage(); await page.setContent(html); page.goto = async () => ({ status: () => 200 }); page.url = () => url; return { newPage: async () => page, close: async () => browser.close() }; }, close: async () => {} }) }); }
test('validates canonical matching LiveJasmin requests', () => { assert.equal(validateRequest(request).ok, true); assert.equal(validateRequest({ ...request, provider: 'other' }).ok, false); assert.equal(validateRequest({ ...request, username: 'Other' }).ok, false); });
test('complete fixture extracts all public candidate fields without HTML', async () => { const result = await fixtureFetch(fixture('profile-complete.html')); assert.equal(result.status, 'ok'); assert.equal(result.raw_fields.schedule, 'Weekdays 18:00 UTC'); assert.equal(result.attributes.country, 'Romania'); assert.equal(result.attributes.profile_image_url, 'https://www.livejasmin.com/image.jpg'); assert.deepEqual(result.diagnostics.fields_found.sort(), ['age','bio','body_type','country','display_name','eye_color','hair_color','height_cm','languages','orientation','profile_image_url','rating','rating_count','schedule','tags'].sort()); assert.equal(result.raw_fields.bio.includes('<b>'), false); });
test('sparse fixture leaves missing fields empty and protected fixtures remain non-successes', async () => { const sparse = await fixtureFetch(fixture('profile-sparse.html')); assert.equal(sparse.status, 'ok'); assert.equal(sparse.raw_fields.bio, ''); assert.equal(sparse.attributes.age, null); assert.deepEqual(sparse.attributes.languages, []); assert.equal((await fixtureFetch(fixture('captcha.html'))).status, 'captcha'); assert.equal((await fixtureFetch(fixture('login-wall.html'))).status, 'login_required'); assert.equal((await fixtureFetch(fixture('profile-complete.html'), 'https://www.livejasmin.com/en/chat/Other')).status, 'blocked'); });

test('invalid numeric labels normalize to null and are absent from fields_found', async () => { const result = await fixtureFetch(fixture('profile-invalid-numbers.html')); assert.equal(result.status, 'ok'); assert.equal(result.attributes.age, null); assert.equal(result.attributes.height_cm, null); assert.equal(result.attributes.rating, null); assert.equal(result.attributes.rating_count, null); for (const key of ['age', 'height_cm', 'rating', 'rating_count']) assert.equal(result.diagnostics.fields_found.includes(key), false); assert.deepEqual(result.diagnostics.fields_found.sort(), ['country', 'display_name']); });
