<?php
namespace TMWSEO\Engine\Content;

use TMWSEO\Engine\Logs;
use TMWSEO\Engine\Jobs;
use TMWSEO\Engine\Services\Settings;
use TMWSEO\Engine\Services\TitleFixer;
use TMWSEO\Engine\Services\OpenAI;
use TMWSEO\Engine\Services\Anthropic;
use TMWSEO\Engine\Platform\PlatformProfiles;
use TMWSEO\Engine\Content\AssistedDraftEnrichmentService;
use TMWSEO\Engine\Content\ContentGenerationGate;
use TMWSEO\Engine\Content\ClaudeContent;

if (!defined('ABSPATH')) { exit; }

class ContentEngine {

    /**
     * Phase A hard fence: legacy publish-trigger autopilot must stay OFF.
     *
     * Deliberate migration path (future phase, not now):
     * 1) add a migration that explicitly flips this via filter,
     * 2) ship rollout checks + tests,
     * 3) document operational runbook.
     */
    private const PHASE_A_PUBLISH_AUTOPILOT_HARD_FENCE = true;

    // Audit fix 4.4.0: model page content floor for AI retry loop.
    // Model page word count contract — all generation paths must respect this.
    // Hard floor: 800 words (fail/retry gate).
    // Preferred target: 1200–1501 words (what pad_model_content and LLM prompts aim for).
    // This is NOT a universal target — actual scoring uses page-type-aware
    // ranges in QualityScoreEngine::word_count_ranges().
    private const MODEL_MIN_WORDS = 800;
    private const MODEL_MIN_KEYWORD_DENSITY = 1.0;
    private const MODEL_MAX_KEYWORD_DENSITY = 2.0;

    private const PREVIEW_TEMPLATE_CATEGORY_PAGE = 'category_page';
    private const PREVIEW_TEMPLATE_MODEL_PAGE = 'model_page';
    private const PREVIEW_TEMPLATE_VIDEO_PAGE = 'video_page';
    private const PREVIEW_TEMPLATE_GENERIC_POST = 'generic_post';

    /** Post types we auto-optimize on first publish */
    private static array $auto_types = [
        'post',
        'page',
        'model',
        'tmw_category_page',
    ];

    private static function is_publish_autopilot_allowed(): bool {
        if (self::PHASE_A_PUBLISH_AUTOPILOT_HARD_FENCE) {
            return false;
        }

        /**
         * Future migration gate.
         *
         * Intentionally defaults to false. A dedicated migration must opt-in
         * with an explicit filter override.
         */
        return (bool) apply_filters('tmwseo_allow_publish_autopilot_hooks', false);
    }

    public static function init(): void {
        // Phase A safety fence: keep legacy autopilot-on-publish hook disconnected.
        if (self::is_publish_autopilot_allowed()) {
            add_action('transition_post_status', [__CLASS__, 'on_transition_post_status'], 10, 3);
        } else {
            Logs::info('content', '[TMW-SEO-AUTO] Phase A hard fence active: transition_post_status autopilot hook is OFF');
        }

        // Shortcode: show generated keyword (for templates)
        add_shortcode('tmwseo_keyword', function($atts){
            $post_id = get_the_ID();
            $kw = get_post_meta($post_id, '_tmwseo_keyword', true);
            return esc_html((string)$kw);
        });

        // Programmatic bulk repair hook for legacy weak model SEO titles.
        add_action('tmwseo_repair_model_seo_titles', [__CLASS__, 'repair_model_seo_titles'], 10, 2);
    }

    /**
     * Repair weak autogenerated Rank Math SEO titles for model posts in bulk.
     *
     * @return array{scanned:int,updated:int}
     */
    public static function repair_model_seo_titles(int $limit = 200, int $offset = 0): array {
        $limit = max(1, min(1000, $limit));
        $offset = max(0, $offset);

        $posts = get_posts([
            'post_type' => 'model',
            'post_status' => ['publish', 'draft', 'pending', 'future', 'private'],
            'posts_per_page' => $limit,
            'offset' => $offset,
            'fields' => 'ids',
            'orderby' => 'ID',
            'order' => 'ASC',
        ]);

        $updated = 0;
        foreach ($posts as $post_id) {
            $post_id = (int) $post_id;
            $name = trim((string) get_the_title($post_id));
            $current_title = trim((string) get_post_meta($post_id, 'rank_math_title', true));
            $is_weak = TemplateContent::is_weak_auto_model_title($current_title, $name);
            if (!$is_weak) {
                continue;
            }

            $new_title = TemplateContent::build_default_model_seo_title($name, '', $post_id);
            if ($new_title === '' || $new_title === $current_title) {
                continue;
            }

            update_post_meta($post_id, 'rank_math_title', $new_title);
            $updated++;
        }

        return [
            'scanned' => count($posts),
            'updated' => $updated,
        ];
    }

    public static function on_transition_post_status(string $new_status, string $old_status, \WP_Post $post): void {
        if (!self::is_publish_autopilot_allowed()) {
            // Defensive double-fence: even if this callback is wired manually, do nothing.
            Logs::warn('content', '[TMW-SEO-AUTO] Blocked legacy publish-trigger autopilot path (Phase A hard fence)', [
                'post_id' => (int) $post->ID,
                'post_type' => (string) $post->post_type,
                'new_status' => (string) $new_status,
                'old_status' => (string) $old_status,
            ]);
            return;
        }

        if ($new_status !== 'publish' || $old_status === 'publish') return;
        if (!in_array($post->post_type, self::$auto_types, true)) return;

        // Only auto-optimize once.
        if (get_post_meta($post->ID, '_tmwseo_optimize_done', true)) return;
        if (get_post_meta($post->ID, '_tmwseo_optimize_enqueued', true)) return;
        if (Settings::is_human_approval_required()) return;

        update_post_meta($post->ID, '_tmwseo_optimize_enqueued', 1);

        Jobs::enqueue('optimize_post', $post->post_type, (int)$post->ID, [
            'context' => self::infer_context($post),
            'trigger' => 'publish',
        ]);

        Logs::info('content', 'Enqueued optimize_post on publish', ['post_id' => $post->ID, 'post_type' => $post->post_type]);
    }

    private static function infer_context(\WP_Post $post): string {
        if ($post->post_type === 'model') return 'model';
        if ($post->post_type === 'tmw_category_page') return 'category_page';
        if ($post->post_type === 'page' && get_post_meta($post->ID, '_tmwseo_generated', true)) return 'keyword_page';
        return 'video_or_post';
    }

    /**
     * Preview-only helper for assisted draft content generation.
     *
     * @param array<string,mixed> $keyword_pack
     * @return array<string,mixed>
     */
    public static function build_preview_only_content_assist(\WP_Post $post, array $keyword_pack = []): array {
        $post_id = (int) $post->ID;

        // ── Architecture v5.0: Content Generation Gate ────────────
        // Block content generation if prerequisites are not met or system is paused.
        if ( class_exists( ContentGenerationGate::class ) ) {
            $gate = ContentGenerationGate::evaluate( $post_id );
            if ( ! $gate['allowed'] ) {
                Logs::info( 'content', '[TMW-CONTENT] Generation blocked by ContentGenerationGate', [
                    'post_id' => $post_id,
                    'reasons' => $gate['reasons'],
                ] );
                return [
                    'ok'      => false,
                    'blocked' => true,
                    'reasons' => $gate['reasons'],
                    'post_id' => $post_id,
                ];
            }
        }

        $dry_run = (int) Settings::get('tmwseo_dry_run_mode', 0) === 1;
        // Respect an explicit strategy passed via keyword_pack['strategy'] or fall back to auto-detect.
        $requested_strategy = sanitize_key((string)($keyword_pack['strategy'] ?? ''));
        $ai_primary = trim((string) Settings::get('tmwseo_ai_primary', 'openai'));
        if ($requested_strategy === 'claude' && Anthropic::is_configured() && $post->post_type === 'model') {
            $strategy = 'claude';
        } elseif ($requested_strategy === 'template') {
            $strategy = 'template';
        } elseif ($requested_strategy === 'openai' && OpenAI::is_configured()) {
            $strategy = 'openai';
        } elseif ($dry_run) {
            $strategy = 'template';
        } elseif ($post->post_type === 'model' && Anthropic::is_configured() && $ai_primary === 'anthropic') {
            $strategy = 'claude';
        } elseif (OpenAI::is_configured()) {
            $strategy = 'openai';
        } elseif ($post->post_type === 'model' && Anthropic::is_configured()) {
            $strategy = 'claude';
        } else {
            $strategy = 'template';
        }
        $context = self::infer_context($post);
        $focus_kw = '';

        if ($post->post_type === 'model' && !empty($keyword_pack['primary'])) {
            $focus_kw = (string) $keyword_pack['primary'];
        }

        if ($focus_kw === '') {
            $focus_kw = trim((string) get_post_meta($post_id, '_tmwseo_keyword', true));
            if ($focus_kw === '') {
                $focus_kw = trim((string) $post->post_title);
            }
        }

        $focus_kw = AssistedDraftEnrichmentService::normalize_focus_keyword_for_post($post, $focus_kw);
        $template_type = self::resolve_preview_template_type($post, $context);

        $secondary_keywords = [];
        if ($post->post_type === 'model') {
            $secondary_keywords = (!empty($keyword_pack['additional']) && is_array($keyword_pack['additional']))
                ? array_slice(array_values(array_filter(array_map('strval', $keyword_pack['additional']))), 0, 4)
                : AssistedDraftEnrichmentService::build_model_secondary_keywords($focus_kw);
        }

        if ($strategy === 'template') {
            $template_preview = self::build_template_preview_payload($post, $keyword_pack, $focus_kw, $template_type);
            $seo_title = (string) ($template_preview['seo_title'] ?? '');
            $meta_desc = (string) ($template_preview['meta_description'] ?? '');
            $generated_content = (string) ($template_preview['content_html'] ?? '');
            $outline = (string) ($template_preview['outline'] ?? self::extract_outline_from_html($generated_content));

            $quality = QualityScoreEngine::evaluate($generated_content, [
                'primary_keyword' => $focus_kw,
                'secondary_keywords' => $secondary_keywords,
                'page_type' => $context,
                'post_type' => (string) $post->post_type,
                'post_id'   => $post_id,
                'entities' => array_values(array_filter(array_unique(array_merge(
                    [$focus_kw, (string) $post->post_title],
                    !empty($keyword_pack['longtail']) && is_array($keyword_pack['longtail'])
                        ? array_slice(array_values(array_filter(array_map('strval', $keyword_pack['longtail']))), 0, 6)
                        : []
                )))),
            ]);

            return [
                'strategy' => $dry_run ? 'template_dry_run' : 'template',
                'template_type' => $template_type,
                'seo_title' => $seo_title,
                'meta_description' => $meta_desc,
                'focus_keyword' => $focus_kw,
                'keyword_pack_summary' => self::build_keyword_pack_summary($keyword_pack),
                'content_html' => wp_kses_post(trim($generated_content)),
                'outline' => $outline,
                'quality_summary' => $quality,
                'generated_at' => current_time('mysql'),
            ];
        }

        // ── Claude (Anthropic) preview strategy ─────────────────────────────
        if ($strategy === 'claude' && $post->post_type === 'model') {
            $claude_result = ClaudeContent::build_model($post, $keyword_pack);
            if ($claude_result['ok']) {
                $support_payload  = TemplateContent::build_model_renderer_support_payload($post, $keyword_pack);
                $renderer_payload = array_merge($support_payload, $claude_result['payload']);
                $html = ModelPageRenderer::render((string)$post->post_title, $renderer_payload);
                $html = wp_kses_post(trim($html));

                // Always use canonical builder for model pages — provider titles
                // may miss a number or sentiment word required by Rank Math.
                $fallback_name = trim((string)($keyword_pack['primary'] ?? $focus_kw ?: $post->post_title));
                $seo_title = TemplateContent::build_default_model_seo_title($fallback_name, '', $post_id);
                $meta_desc = (string)($claude_result['meta_description'] ?? '');
                $generated_focus_kw = AssistedDraftEnrichmentService::normalize_focus_keyword_for_post(
                    $post,
                    (string)($claude_result['focus_keyword'] ?? $focus_kw)
                );

                $quality = QualityScoreEngine::evaluate($html, [
                    'primary_keyword'    => $generated_focus_kw,
                    'secondary_keywords' => $secondary_keywords,
                    'page_type'          => $context,
                    'post_type'          => (string)$post->post_type,
                    'post_id'            => $post_id,
                    'entities'           => array_values(array_filter(array_unique([$generated_focus_kw, (string)$post->post_title]))),
                ]);

                return [
                    'strategy'             => 'claude',
                    'template_type'        => $template_type,
                    'seo_title'            => $seo_title,
                    'meta_description'     => $meta_desc,
                    'focus_keyword'        => $generated_focus_kw,
                    'keyword_pack_summary' => self::build_keyword_pack_summary($keyword_pack),
                    'content_html'         => $html,
                    'outline'              => self::extract_outline_from_html($html),
                    'quality_summary'      => $quality,
                    'generated_at'         => current_time('mysql'),
                ];
            }

            // Claude failed in preview — fall through to OpenAI.
            Logs::warn('content', '[TMW-CLAUDE] Claude preview failed, falling back to openai', [
                'post_id' => $post_id,
                'error'   => $claude_result['error'] ?? 'unknown',
            ]);
        }
        // BUG-FIX: $clean_title was undefined here — must derive it from post_title
        // before building $clean_title_short for the OpenAI system prompt.
        $clean_title       = TitleFixer::fix((string) $post->post_title);
        $clean_title_short = TitleFixer::shorten($clean_title, 70);
        $model = Settings::openai_model_for_quality();
        $is_model_page = ($post->post_type === 'model');
        $length_hint = ($context === 'keyword_page' || $context === 'category_page') ? '500-800 words' : ($context === 'model' ? '1200-1501 words' : '150-350 words');

        $system = [
            'role' => 'system',
            'content' =>
                "You are a professional SEO copywriter for top-models.webcam.\n" .
                "Write informative, human-readable content about adult webcam / live video chat.\n" .
                "Keep language non-explicit and safe: do NOT describe graphic sexual acts.\n" .
                "Focus on user intent (features, safety, privacy, etiquette, what to expect).\n" .
                "Output STRICT JSON with keys: seo_title, meta_description, focus_keyword, intro_paragraphs, watch_section_paragraphs, about_section_paragraphs, fans_like_section_paragraphs, features_section_paragraphs, comparison_section_paragraphs, faq_items.\n" .
                "seo_title <= 65 characters. meta_description 145-160 characters.\n" .
                "Do not include h1 or raw section HTML architecture in any JSON value.\n" .
                "PROSE QUALITY RULES (non-negotiable):\n" .
                "- Never repeat the exact focus keyword more than twice in a single paragraph.\n" .
                "- Keep the exact model name natural; do not force pronouns as a density fix, and never rewrite usernames or literal keyword phrases.\n" .
                "- Do not begin more than one paragraph across ALL sections with 'Viewers who', 'People looking up', or 'Searches for/around'.\n" .
                "- faq_items answers must be 2-3 complete sentences each and should read like straightforward replies, not mini essays.\n" .
                "- Vary sentence length and opener across sections.\n" .
                "- Avoid signposting such as 'This guide covers', 'Here\'s what to know', or 'Let\'s dive in'.\n" .
                "- Avoid brochure phrasing, vague importance claims, and formulaic contrasts like 'it\'s not just X, it\'s Y'. Use direct sentences.\n" .
                "- Avoid the phrases 'official live profile' and 'trusted room links' entirely.\n" .
                "- Use 'official profile links' at most once across the entire output.\n"
        ];

        $user_content =
            "PAGE CONTEXT\n" .
            "- Post type: {$post->post_type}\n" .
            "- Context: {$context}\n" .
            "- Current title (cleaned): {$clean_title_short}\n" .
            ($focus_kw ? "- Primary keyword (must be used exactly): {$focus_kw}\n" : '') .
            (!empty($secondary_keywords) ? "- Secondary keywords (sprinkle naturally): " . implode(', ', $secondary_keywords) . "\n" : '') .
            (!empty($keyword_pack['longtail']) && is_array($keyword_pack['longtail']) ? "- Long-tail queries to cover: " . implode('; ', array_slice($keyword_pack['longtail'], 0, 6)) . "\n" : '') .
            "- Target length: {$length_hint}\n\n" .
            "WRITE:\n" .
            "1) SEO title that matches the page and includes the keyword naturally.\n" .
            "2) Meta description with a clear value proposition.\n" .
            "3) One focus keyword (short).\n" .
            "4) Provide section paragraph arrays and faq_items (3-5 Q&As).\n";

        if ($is_model_page) {
            $user_content .= "\nMODEL PAGE TEMPLATE (required):\n" .
                "- Return ONLY structured JSON fields — no HTML headings, no raw HTML in values:\n" .
                "  intro_paragraphs (2-3 items), watch_section_paragraphs (1-2 items), about_section_paragraphs (2-3 items),\n" .
                "  fans_like_section_paragraphs (2-3 items), features_section_paragraphs (2-3 items),\n" .
                "  comparison_section_paragraphs (1-2 items), faq_items (4-5 objects with q and a keys).\n" .
                "- Ensure the primary keyword appears naturally in intro_paragraphs[0] and at least two other sections.\n" .
                "- Hard minimum word count across all prose sections: " . self::MODEL_MIN_WORDS . " words.\n" .
                "- Preferred target: 1200–1501 words — expand each section generously to reach this.\n" .
                "- Each section must contain at least 80 words.\n" .
                "- Use varied paragraph openers — never start two consecutive paragraphs the same way.\n" .
                "- Keep exact focus-keyword density between " . self::MODEL_MIN_KEYWORD_DENSITY . "% and " . self::MODEL_MAX_KEYWORD_DENSITY . "%.\n" .
                "- fans_like_section_paragraphs: describe what keeps viewers coming back — use varied sentence structures, not a repeated formula.\n" .
                "- Weave the four secondary keywords lightly and naturally; do not dump them as a list or repeat them mechanically.\n" .
                "- Use concrete observations about pace, chat style, scheduling, privacy, or room features instead of generic filler.\n" .
                "- faq_items: write natural questions real viewers would ask; answers must be 2-3 complete sentences.\n";
        } elseif ($template_type === self::PREVIEW_TEMPLATE_CATEGORY_PAGE) {
            $user_content .= "\nCATEGORY PAGE TEMPLATE (required):\n" .
                "- Purpose: help users compare and choose options within this category intent.\n" .
                "- Use this heading structure in content_html:\n" .
                "  H1: Best {$focus_kw} Sites\n" .
                "  H2: What to Expect From {$focus_kw}\n" .
                "  H2: How to Choose the Right {$focus_kw} Platform\n" .
                "  H2: Features That Matter for {$focus_kw}\n" .
                "  H2: Safety, Privacy, and Billing Tips\n" .
                "  H2: FAQ About {$focus_kw}\n" .
                "- Include a short related-subtopics block near the end using an unordered list.\n" .
                "- Keep sections practical, comparison-focused, and category-intent aligned.\n";
        } elseif ($template_type === self::PREVIEW_TEMPLATE_VIDEO_PAGE) {
            $user_content .= "\nVIDEO PAGE TEMPLATE (required):\n" .
                "- Focus on watch intent and user expectations for the specific video topic.\n" .
                "- Include: H1, 3-5 H2 sections, and a short FAQ.\n";
        } else {
            $user_content .= "\nGENERIC POST TEMPLATE (required):\n" .
                "- Provide an informative explainer structure with H1, 3-4 H2 sections, and FAQ.\n";
        }
        $res = OpenAI::chat_json([
            $system,
            ['role' => 'user', 'content' => $user_content],
        ], $model, [
            'temperature' => 0.6,
            'max_tokens' => $is_model_page ? 4096 : 2200,
        ]);

        if (!$res['ok']) {
            return [
                'strategy' => 'openai',
                'error' => (string) ($res['error'] ?? 'generation_failed'),
                'generated_at' => current_time('mysql'),
            ];
        }

        $j = is_array($res['json'] ?? null) ? $res['json'] : [];
        $seo_title = TitleFixer::shorten(trim((string) ($j['seo_title'] ?? '')), 60);
        if ($is_model_page) {
            // Always replace with the canonical builder for model pages — provider
            // titles may satisfy the length limit but miss a required number or
            // sentiment word. The canonical builder is deterministic and guaranteed
            // to satisfy all Rank Math title requirements.
            $fallback_name = trim((string)($keyword_pack['primary'] ?? $focus_kw ?: $post->post_title));
            $seo_title = TemplateContent::build_default_model_seo_title($fallback_name, '', $post_id);
        }
        $meta_desc = trim((string) ($j['meta_description'] ?? ''));
        $generated_focus_kw = trim((string) ($j['focus_keyword'] ?? ''));
        if ($is_model_page && !empty($keyword_pack['primary'])) {
            $generated_focus_kw = (string) $keyword_pack['primary'];
        }
        $generated_focus_kw = AssistedDraftEnrichmentService::normalize_focus_keyword_for_post($post, $generated_focus_kw !== '' ? $generated_focus_kw : $focus_kw);
        $html = trim((string) ($j['content_html'] ?? ''));

        if ($is_model_page) {
            $support_payload = TemplateContent::build_model_renderer_support_payload($post, $keyword_pack);
            $renderer_payload = array_merge($support_payload, self::extract_model_renderer_payload($j));
            $html = ModelPageRenderer::render((string)$post->post_title, $renderer_payload);
            $validated = self::enforce_model_content_constraints([$system, ['role' => 'user', 'content' => $user_content]], $model, 3200, $generated_focus_kw, $html, $j, (string)$post->post_title, $support_payload);
            $html = (string) ($validated['html'] ?? $html);
            $generated_focus_kw = trim((string) ($validated['focus_keyword'] ?? $generated_focus_kw));
        }

        $html = wp_kses_post($html);

        $quality = QualityScoreEngine::evaluate($html, [
            'primary_keyword' => $generated_focus_kw,
            'secondary_keywords' => $secondary_keywords,
            'page_type' => $context,
            'post_type' => (string) $post->post_type,
            'post_id'   => $post_id,
            'entities' => array_values(array_filter(array_unique(array_merge(
                [$generated_focus_kw, (string) $post->post_title],
                !empty($keyword_pack['longtail']) && is_array($keyword_pack['longtail'])
                    ? array_slice(array_values(array_filter(array_map('strval', $keyword_pack['longtail']))), 0, 6)
                    : []
            )))),
        ]);

        return [
            'strategy' => 'openai',
            'template_type' => $template_type,
            'seo_title' => $seo_title,
            'meta_description' => $meta_desc,
            'focus_keyword' => $generated_focus_kw,
            'keyword_pack_summary' => self::build_keyword_pack_summary($keyword_pack),
            'content_html' => $html,
            'outline' => self::extract_outline_from_html($html),
            'quality_summary' => $quality,
            'generated_at' => current_time('mysql'),
        ];
    }

    private static function resolve_preview_template_type(\WP_Post $post, string $context): string {
        if ($post->post_type === 'tmw_category_page' || $context === 'category_page') {
            return self::PREVIEW_TEMPLATE_CATEGORY_PAGE;
        }

        if ($post->post_type === 'model' || $context === 'model') {
            return self::PREVIEW_TEMPLATE_MODEL_PAGE;
        }

        if ($post->post_type === 'post' || $context === 'video_or_post') {
            return self::PREVIEW_TEMPLATE_VIDEO_PAGE;
        }

        return self::PREVIEW_TEMPLATE_GENERIC_POST;
    }

    /**
     * @param array<string,mixed> $keyword_pack
     * @return array<string,string>
     */
    private static function build_template_preview_payload(\WP_Post $post, array $keyword_pack, string $focus_kw, string $template_type): array {
        if ($template_type === self::PREVIEW_TEMPLATE_MODEL_PAGE) {
            $tpl = \TMWSEO\Engine\Content\TemplateContent::build_model($post, $keyword_pack);
            return [
                'seo_title' => TitleFixer::shorten((string) ($tpl['seo_title'] ?? ''), 70),
                'meta_description' => TitleFixer::shorten((string) ($tpl['meta_description'] ?? ''), 160),
                'content_html' => (string) ($tpl['content'] ?? ''),
                'outline' => self::extract_outline_from_html((string) ($tpl['content'] ?? '')),
            ];
        }

        if ($template_type === self::PREVIEW_TEMPLATE_CATEGORY_PAGE) {
            return self::build_category_page_template_preview($post, $focus_kw, $keyword_pack);
        }

        if ($template_type === self::PREVIEW_TEMPLATE_VIDEO_PAGE) {
            return self::build_video_page_template_preview($post, $focus_kw);
        }

        return self::build_generic_post_template_preview($post, $focus_kw);
    }

    /**
     * @param array<string,mixed> $keyword_pack
     * @return array<string,string>
     */
    private static function build_category_page_template_preview(\WP_Post $post, string $focus_kw, array $keyword_pack): array {
        $blog_name = (string) get_bloginfo('name');
        $category_term = $focus_kw !== '' ? $focus_kw : (string) $post->post_title;
        $seo_title = TitleFixer::shorten('Best ' . $category_term . ' Sites: Features, Safety & Tips', 70);
        $meta_description = TitleFixer::shorten('Compare top ' . $category_term . ' options with safety tips, feature breakdowns, and practical guidance to choose the right live chat platform.', 160);

        $related_topics = !empty($keyword_pack['longtail']) && is_array($keyword_pack['longtail'])
            ? array_slice(array_values(array_filter(array_map('strval', $keyword_pack['longtail']))), 0, 4)
            : [];

        $related_block = '';
        if (!empty($related_topics)) {
            $items = '';
            foreach ($related_topics as $topic) {
                $items .= '<li>' . esc_html($topic) . '</li>';
            }
            $related_block = '<h2>Related ' . esc_html($category_term) . ' Subtopics</h2><ul>' . $items . '</ul>';
        }

        $content =
            '<h1>Best ' . esc_html($category_term) . ' Sites</h1>' .
            '<p>This draft preview helps visitors evaluate <strong>' . esc_html($category_term) . '</strong> options quickly, with emphasis on trust, feature fit, and user intent.</p>' .
            '<h2>What to Expect From ' . esc_html($category_term) . '</h2>' .
            '<p>Explain the category scope, common user goals, and the kinds of experiences people usually want from this page type.</p>' .
            '<h2>How to Choose the Right ' . esc_html($category_term) . ' Platform</h2>' .
            '<p>Provide practical selection criteria: onboarding quality, performer variety, language support, and platform reliability.</p>' .
            '<h2>Features That Matter for ' . esc_html($category_term) . '</h2>' .
            '<ul><li>Search/filter depth for faster matching</li><li>Transparent pricing and token options</li><li>Mobile and desktop usability</li></ul>' .
            '<h2>Safety, Privacy, and Billing Tips</h2>' .
            '<p>Include concise guidance on account security, payment clarity, and personal boundaries when using live chat products.</p>' .
            '<h2>FAQ About ' . esc_html($category_term) . '</h2>' .
            '<h3>How do I compare options in this category?</h3><p>Use the same shortlist criteria across platforms to make a fair comparison.</p>' .
            '<h3>What should I check before spending?</h3><p>Review billing terms, trial options, and moderation/safety settings first.</p>' .
            $related_block .
            '<p><em>Preview intent summary:</em> This category-page draft is structured for taxonomy intent and operator review before any manual draft apply in ' . esc_html($blog_name) . '.</p>';

        return [
            'seo_title' => $seo_title,
            'meta_description' => $meta_description,
            'content_html' => $content,
            'outline' => "- Best {$category_term} Sites\n- What to Expect From {$category_term}\n- How to Choose the Right {$category_term} Platform\n- Features That Matter for {$category_term}\n- Safety, Privacy, and Billing Tips\n- FAQ About {$category_term}",
        ];
    }

    /** @return array<string,string> */
    private static function build_video_page_template_preview(\WP_Post $post, string $focus_kw): array {
        // Audit fix 4.4.0: use VideoContentArchitecture instead of placeholder skeleton.
        if (class_exists('\\TMWSEO\\Engine\\Content\\VideoContentArchitecture')) {
            $preview = \TMWSEO\Engine\Content\VideoContentArchitecture::build_preview($post);
            return [
                'seo_title'        => (string) ($preview['seo_title'] ?? ''),
                'meta_description' => (string) ($preview['meta_description'] ?? ''),
                'content_html'     => (string) ($preview['content_html'] ?? ''),
                'outline'          => (string) ($preview['outline'] ?? ''),
            ];
        }

        // Legacy fallback (should not be reached).
        $topic = $focus_kw !== '' ? $focus_kw : (string) $post->post_title;
        return [
            'seo_title' => TitleFixer::shorten($topic . ' Video Guide: What to Watch For', 70),
            'meta_description' => TitleFixer::shorten('A practical preview guide for ' . $topic . ' with viewing tips, feature highlights, and safety guidance before you choose a platform.', 160),
            'content_html' => '<h1>' . esc_html($topic) . ' Video Guide</h1><p>This preview is designed for video-intent readers seeking practical context before they watch.</p>',
            'outline' => "- {$topic} Video Guide",
        ];
    }

    /** @return array<string,string> */
    private static function build_generic_post_template_preview(\WP_Post $post, string $focus_kw): array {
        $topic = $focus_kw !== '' ? $focus_kw : (string) $post->post_title;
        return [
            'seo_title' => TitleFixer::shorten(TitleFixer::fix((string) $post->post_title), 70),
            'meta_description' => TitleFixer::shorten('Learn more about ' . $topic . ' with a structured draft preview focused on user intent and practical guidance.', 160),
            'content_html' => '<h1>' . esc_html($topic) . '</h1><p>Preview-only draft starter for manual editorial review.</p><h2>Overview</h2><p>Introduce the topic and user intent.</p><h2>Key Points</h2><p>Cover the most important considerations.</p><h2>FAQ</h2><h3>Where should readers begin?</h3><p>Start with the overview and compare options based on goals.</p>',
            'outline' => "- {$topic}\n- Overview\n- Key Points\n- FAQ",
        ];
    }

    /** @param array<string,mixed> $keyword_pack */
    private static function build_keyword_pack_summary(array $keyword_pack): string {
        $primary = trim((string) ($keyword_pack['primary'] ?? ''));
        $additional = !empty($keyword_pack['additional']) && is_array($keyword_pack['additional'])
            ? array_slice(array_values(array_filter(array_map('strval', $keyword_pack['additional']))), 0, 4)
            : [];
        $longtail = !empty($keyword_pack['longtail']) && is_array($keyword_pack['longtail'])
            ? array_slice(array_values(array_filter(array_map('strval', $keyword_pack['longtail']))), 0, 6)
            : [];

        return trim(
            ($primary !== '' ? 'Primary: ' . $primary . '. ' : '') .
            (!empty($additional) ? 'Additional: ' . implode(', ', $additional) . '. ' : '') .
            (!empty($longtail) ? 'Long-tail: ' . implode('; ', $longtail) . '.' : '')
        );
    }

    private static function extract_outline_from_html(string $html): string {
        if (trim($html) === '') {
            return '';
        }

        preg_match_all('/<h[1-3][^>]*>(.*?)<\/h[1-3]>/is', $html, $matches);
        $items = [];
        if (!empty($matches[1]) && is_array($matches[1])) {
            foreach ($matches[1] as $heading) {
                $clean = trim((string) wp_strip_all_tags((string) $heading));
                if ($clean !== '') {
                    $items[] = $clean;
                }
            }
        }

        if (empty($items)) {
            return '';
        }

        return implode("\n", array_map(static function (string $item): string {
            return '- ' . $item;
        }, $items));
    }


    private static function should_bootstrap_model_generation( \WP_Post $post, array $payload, bool $keywords_only ): bool {
        if ( $post->post_type !== 'model' || $keywords_only ) {
            return false;
        }

        if ( ! empty( $payload['manual_model_generate'] ) ) {
            return true;
        }

        return sanitize_key( (string) ( $payload['trigger'] ?? '' ) ) === 'manual';
    }

    /**
     * @param array<string,mixed> $payload
     * @return array{primary:string,additional:string[],longtail:string[],sources:array<string,mixed>}
     */
    private static function bootstrap_model_generation_prereqs( \WP_Post $post, array $payload = [] ): array {
        $pack = [
            'primary'    => '',
            'additional' => [],
            'longtail'   => [],
            'sources'    => [],
        ];

        if ( class_exists( AssistedDraftEnrichmentService::class )
            && method_exists( AssistedDraftEnrichmentService::class, 'build_and_store_keyword_pack_for_post' ) ) {
            try {
                $generated = AssistedDraftEnrichmentService::build_and_store_keyword_pack_for_post( $post, true );
                if ( is_array( $generated ) ) {
                    $pack = array_merge( $pack, $generated );
                }
            } catch ( \Throwable $e ) {
                Logs::warn( 'content', '[TMW-MODEL-BOOTSTRAP] Keyword pack generation failed; using starter fallback', [
                    'post_id' => (int) $post->ID,
                    'error'   => $e->getMessage(),
                ] );
            }
        }

        $pack = self::normalize_model_keyword_pack( $post, $pack, $payload );
        self::sync_model_generation_bootstrap_meta( $post, $pack );

        return $pack;
    }

    /**
     * @param array<string,mixed> $pack
     * @param array<string,mixed> $payload
     * @return array{primary:string,additional:string[],longtail:string[],sources:array<string,mixed>}
     */
    private static function normalize_model_keyword_pack( \WP_Post $post, array $pack, array $payload = [] ): array {
        $platforms = self::collect_model_platform_snapshot( (int) $post->ID );

        $primary = trim( (string) ( $pack['primary'] ?? '' ) );
        if ( $primary === '' ) {
            $primary = trim( (string) get_post_meta( $post->ID, '_tmwseo_keyword', true ) );
        }
        if ( $primary === '' ) {
            $rank_math_focus = trim( (string) get_post_meta( $post->ID, 'rank_math_focus_keyword', true ) );
            if ( $rank_math_focus !== '' ) {
                $rank_parts = array_values( array_filter( array_map( 'trim', explode( ',', $rank_math_focus ) ) ) );
                $primary = (string) ( $rank_parts[0] ?? '' );
            }
        }
        if ( $primary === '' ) {
            $primary = trim( (string) ( $payload['keyword'] ?? '' ) );
        }
        if ( $primary === '' ) {
            $primary = trim( (string) $post->post_title );
        }
        if ( $primary === '' ) {
            $primary = 'Live Cam Model';
        }

        $primary = AssistedDraftEnrichmentService::normalize_focus_keyword_for_post( $post, $primary );

        $additional = is_array( $pack['additional'] ?? null ) ? $pack['additional'] : [];
        $additional = array_values( array_filter( array_map( 'trim', $additional ), 'strlen' ) );
        $additional = array_values( array_unique( array_merge( $additional, self::starter_model_additional_keywords( $primary, $platforms ) ) ) );
        $additional = array_slice( $additional, 0, 8 );

        $longtail = is_array( $pack['longtail'] ?? null ) ? $pack['longtail'] : [];
        $longtail = array_values( array_filter( array_map( 'trim', $longtail ), 'strlen' ) );
        $longtail = array_values( array_unique( array_merge( $longtail, self::starter_model_longtail_keywords( $primary, $platforms ) ) ) );
        $longtail = array_slice( $longtail, 0, 8 );

        $sources = is_array( $pack['sources'] ?? null ) ? $pack['sources'] : [];
        if ( ! isset( $sources['tags'] ) ) {
            $sources['tags'] = self::model_tag_names( $post );
        }
        $sources['bootstrap'] = 'manual_model_generate';
        $sources['platforms'] = $platforms['slugs'];

        return [
            'primary'    => $primary,
            'additional' => $additional,
            'longtail'   => $longtail,
            'sources'    => $sources,
        ];
    }

    /**
     * @param array<string,mixed> $base_pack
     * @param array<string,mixed> $generated_pack
     * @param array<string,mixed> $payload
     * @return array{primary:string,additional:string[],longtail:string[],sources:array<string,mixed>}
     */
    private static function merge_model_keyword_pack( array $base_pack, array $generated_pack, \WP_Post $post, array $payload = [] ): array {
        $pack = [
            'primary'    => trim( (string) ( $generated_pack['primary'] ?? $base_pack['primary'] ?? '' ) ),
            'additional' => array_values( array_unique( array_merge(
                is_array( $base_pack['additional'] ?? null ) ? $base_pack['additional'] : [],
                is_array( $generated_pack['additional'] ?? null ) ? $generated_pack['additional'] : []
            ) ) ),
            'longtail'   => array_values( array_unique( array_merge(
                is_array( $base_pack['longtail'] ?? null ) ? $base_pack['longtail'] : [],
                is_array( $generated_pack['longtail'] ?? null ) ? $generated_pack['longtail'] : []
            ) ) ),
            'sources'    => array_merge(
                is_array( $base_pack['sources'] ?? null ) ? $base_pack['sources'] : [],
                is_array( $generated_pack['sources'] ?? null ) ? $generated_pack['sources'] : []
            ),
        ];

        return self::normalize_model_keyword_pack( $post, $pack, $payload );
    }

    /**
     * @param array{primary:string,additional:string[],longtail:string[],sources:array<string,mixed>} $pack
     */
    private static function sync_model_generation_bootstrap_meta( \WP_Post $post, array $pack ): void {
        $post_id  = (int) $post->ID;
        $primary  = trim( (string) ( $pack['primary'] ?? '' ) );
        $platform = self::collect_model_platform_snapshot( $post_id );

        if ( $primary !== '' ) {
            update_post_meta( $post_id, '_tmwseo_keyword', $primary );
        }

        $confidence_raw = get_post_meta( $post_id, '_tmwseo_keyword_confidence', true );
        if ( $confidence_raw === '' || $confidence_raw === false || (float) $confidence_raw < 10.0 ) {
            update_post_meta( $post_id, '_tmwseo_keyword_confidence', self::starter_model_keyword_confidence( $pack, $platform ) );
        }

        if ( ! empty( $platform['primary_slug'] ) && get_post_meta( $post_id, '_tmwseo_primary_platform', true ) === '' ) {
            update_post_meta( $post_id, '_tmwseo_primary_platform', (string) $platform['primary_slug'] );
        }

        if ( class_exists( AssistedDraftEnrichmentService::class ) && method_exists( AssistedDraftEnrichmentService::class, 'enrich_rank_math_keywords' ) ) {
            AssistedDraftEnrichmentService::enrich_rank_math_keywords( $post, $pack );
        }

        if ( class_exists( '\TMWSEO\Engine\Content\RankMathMapper' ) ) {
            RankMathMapper::sync_to_rank_math( $post_id, $pack, true );
        } elseif ( $primary !== '' ) {
            update_post_meta( $post_id, 'rank_math_focus_keyword', $primary );
            if ( ! empty( $pack['additional'] ) ) {
                update_post_meta( $post_id, 'rank_math_additional_keywords', implode( ', ', array_slice( $pack['additional'], 0, 8 ) ) );
            }
        }
    }

    /**
     * @return array{slugs:string[],labels:string[],primary_slug:string,primary_label:string,count:int}
     */
    private static function collect_model_platform_snapshot( int $post_id ): array {
        $supported = [ 'livejasmin', 'stripchat', 'chaturbate', 'myfreecams', 'camsoda', 'bonga', 'cam4' ];
        $slugs = [];
        $labels = [];
        $primary_slug = '';
        $primary_label = '';

        if ( class_exists( PlatformProfiles::class ) && method_exists( PlatformProfiles::class, 'get_links' ) ) {
            $links = PlatformProfiles::get_links( $post_id );
            if ( is_array( $links ) ) {
                foreach ( $links as $link ) {
                    if ( ! is_array( $link ) ) {
                        continue;
                    }
                    $platform = sanitize_key( (string) ( $link['platform'] ?? '' ) );
                    if ( $platform === '' ) {
                        continue;
                    }
                    if ( ! in_array( $platform, $slugs, true ) ) {
                        $slugs[] = $platform;
                        $platform_meta = class_exists( '\TMWSEO\Engine\Platform\PlatformRegistry' )
                            ? \TMWSEO\Engine\Platform\PlatformRegistry::get( $platform )
                            : [];
                        $labels[] = (string) ( $platform_meta['name'] ?? ucfirst( $platform ) );
                    }
                    if ( empty( $primary_slug ) && ! empty( $link['is_primary'] ) ) {
                        $primary_slug = $platform;
                    }
                }
            }
        }

        foreach ( $supported as $platform ) {
            $username = trim( (string) get_post_meta( $post_id, '_tmwseo_platform_username_' . $platform, true ) );
            if ( $username === '' ) {
                continue;
            }
            if ( ! in_array( $platform, $slugs, true ) ) {
                $slugs[] = $platform;
                $platform_meta = class_exists( '\TMWSEO\Engine\Platform\PlatformRegistry' )
                    ? \TMWSEO\Engine\Platform\PlatformRegistry::get( $platform )
                    : [];
                $labels[] = (string) ( $platform_meta['name'] ?? ucfirst( $platform ) );
            }
        }

        if ( $primary_slug === '' && ! empty( $slugs ) ) {
            $primary_slug = (string) $slugs[0];
        }
        if ( $primary_slug !== '' ) {
            $platform_meta = class_exists( '\TMWSEO\Engine\Platform\PlatformRegistry' )
                ? \TMWSEO\Engine\Platform\PlatformRegistry::get( $primary_slug )
                : [];
            $primary_label = (string) ( $platform_meta['name'] ?? ucfirst( $primary_slug ) );
        }

        return [
            'slugs'         => $slugs,
            'labels'        => array_values( array_unique( array_filter( $labels ) ) ),
            'primary_slug'  => $primary_slug,
            'primary_label' => $primary_label,
            'count'         => count( $slugs ),
        ];
    }

    /** @return string[] */
    private static function starter_model_additional_keywords( string $primary, array $platform ): array {
        $primary_label = trim( (string) ( $platform['primary_label'] ?? '' ) );
        $labels = array_values( array_filter( array_map( 'trim', (array) ( $platform['labels'] ?? [] ) ), 'strlen' ) );
        $secondary_label = $labels[1] ?? '';

        $keywords = [];
        if ( $primary_label !== '' ) {
            $keywords[] = $primary_label . ' schedule';
        }
        if ( $secondary_label !== '' ) {
            $keywords[] = $secondary_label . ' profile';
        } elseif ( $primary_label !== '' ) {
            $keywords[] = $primary_label . ' profile';
        }

        $keywords[] = 'verified profile links';
        $keywords[] = 'private live chat';
        $keywords[] = 'HD live stream';
        $keywords[] = 'real-time chat features';

        return array_slice( array_values( array_unique( array_filter( array_map( 'trim', $keywords ), 'strlen' ) ) ), 0, 4 );
    }

    /** @return string[] */
    private static function starter_model_longtail_keywords( string $primary, array $platform ): array {
        $primary_label = trim( (string) ( $platform['primary_label'] ?? '' ) );
        $keywords = [
            'how to watch live webcam shows',
            'live show schedule',
            'private live chat tips',
            'HD live stream experience',
            'real-time chat features',
            'how to join a live session',
        ];

        if ( $primary_label !== '' ) {
            $keywords[] = $primary_label . ' live show schedule';
            $keywords[] = $primary_label . ' profile guide';
        }

        return array_values( array_unique( array_filter( array_map( 'trim', $keywords ), 'strlen' ) ) );
    }

    /** @return string[] */
    private static function model_tag_names( \WP_Post $post ): array {
        $tags = get_the_terms( $post, 'post_tag' );
        if ( ! is_array( $tags ) ) {
            return [];
        }

        $names = [];
        foreach ( $tags as $tag ) {
            if ( $tag instanceof \WP_Term ) {
                $names[] = (string) $tag->slug;
            }
        }

        return array_values( array_unique( array_filter( $names ) ) );
    }

    /**
     * @param array{primary:string,additional:string[],longtail:string[],sources:array<string,mixed>} $pack
     */
    private static function starter_model_keyword_confidence( array $pack, array $platform ): float {
        $score = 54.0;
        if ( trim( (string) ( $pack['primary'] ?? '' ) ) !== '' ) {
            $score += 8.0;
        }
        $score += min( 10.0, (float) count( $pack['additional'] ?? [] ) * 2.0 );
        $score += min( 8.0, (float) count( $pack['longtail'] ?? [] ) * 1.5 );
        $score += ! empty( $platform['count'] ) ? min( 10.0, (float) $platform['count'] * 3.0 ) : 0.0;

        return min( 82.0, max( 58.0, round( $score, 1 ) ) );
    }

    public static function run_optimize_job(array $job): void {
        $post_id = (int)($job['entity_id'] ?? 0);
        $dry = (int) Settings::get('tmwseo_dry_run_mode', 0);
        if ($post_id <= 0) {
            Logs::warn('content', 'optimize_post missing entity_id');
            return;
        }

        $post = get_post($post_id);
        if (!$post) {
            Logs::warn('content', 'Post not found', ['post_id' => $post_id]);
            return;
        }

        $payload = $job['payload'] ?? [];
        if (!is_array($payload)) {
            $payload = [];
        }

        $insert_block = (int)($payload['insert_block'] ?? 1) === 1;
        $keywords_only = (int)($payload['keywords_only'] ?? 0) === 1 || (int)($payload['refresh_keywords_only'] ?? 0) === 1;

        if (!$keywords_only && Settings::is_safe_mode()) {
            Logs::info('content', 'Safe mode enabled; skipping AI generation', ['post_id' => $post_id]);
            delete_post_meta($post_id, '_tmwseo_optimize_enqueued');
            update_post_meta($post_id, '_tmwseo_optimize_done', 'skipped_safe_mode');
            return;
        }

        // Strategy precedence: explicit payload > settings.
        $strategy = sanitize_key((string)($payload['strategy'] ?? ''));
        if ($strategy === '') {
            $strategy = ((int)$dry === 1) ? 'template' : 'openai';
        }

        $is_manual_model_request = self::is_manual_model_request($post, $payload);

        // Build keyword pack for models first so manual bootstrap can satisfy
        // obvious prerequisites before the content gate blocks generation.
        $keyword_pack = [];
        if ($post->post_type === 'model') {
            $keyword_pack = AssistedDraftEnrichmentService::build_and_store_keyword_pack_for_post($post, true);
            if (class_exists(TemplateContent::class) && method_exists(TemplateContent::class, 'hydrate_model_keyword_pack')) {
                $keyword_pack = TemplateContent::hydrate_model_keyword_pack($post, $keyword_pack);
            }
            if ($is_manual_model_request) {
                $keyword_pack = self::bootstrap_manual_model_generate($post, $keyword_pack);
            }
            AssistedDraftEnrichmentService::enrich_rank_math_keywords($post, $keyword_pack);
        }

        if ($keywords_only) {
            delete_post_meta($post_id, '_tmwseo_optimize_enqueued');
            update_post_meta($post_id, '_tmwseo_optimize_done', 'keywords_refreshed');

            if ($post->post_type === 'model' && !empty($keyword_pack['primary'])) {
                AssistedDraftEnrichmentService::update_model_secondary_keywords_for_post($post, (string)$keyword_pack['primary']);
            }

            Logs::info('content', '[TMW-KEYWORDS] Refreshed keyword pack + RankMath fields only', [
                'post_id' => $post_id,
                'post_type' => $post->post_type,
                'manual_bootstrap' => $is_manual_model_request,
            ]);

            return;
        }

        // ── Architecture v5.0: Content Generation Gate ────────────
        // Preserve the gate globally, but evaluate it AFTER explicit manual
        // model bootstrap so safe prerequisites can be satisfied first.
        if ( class_exists( ContentGenerationGate::class ) ) {
            $gate = ContentGenerationGate::evaluate( $post_id );
            if ( ! $gate['allowed'] ) {
                Logs::info( 'content', '[TMW-CONTENT] Optimization blocked by ContentGenerationGate', [
                    'post_id' => $post_id,
                    'reasons' => $gate['reasons'] ?? [],
                    'manual_bootstrap' => $is_manual_model_request,
                ] );
                delete_post_meta($post_id, '_tmwseo_optimize_enqueued');
                update_post_meta($post_id, '_tmwseo_optimize_done', 'blocked_content_gate');
                return;
            }
        }

        // ── Claude (Anthropic) strategy ──────────────────────────────────────
        if ($strategy === 'claude' && $post->post_type === 'model' && Anthropic::is_configured()) {
            $focus_kw = !empty($keyword_pack['primary'])
                ? (string)$keyword_pack['primary']
                : trim((string)get_post_meta($post_id, '_tmwseo_keyword', true));
            if ($focus_kw === '') $focus_kw = trim((string)$post->post_title);
            $focus_kw = AssistedDraftEnrichmentService::normalize_focus_keyword_for_post($post, $focus_kw);

            $claude_result = ClaudeContent::build_model($post, $keyword_pack);

            if ($claude_result['ok']) {
                $support_payload  = TemplateContent::build_model_renderer_support_payload($post, $keyword_pack);
                $renderer_payload = array_merge($support_payload, $claude_result['payload']);
                $generated_content = ModelPageRenderer::render((string)$post->post_title, $renderer_payload);
                $generated_content = wp_kses_post($generated_content);
                // Always use canonical builder for model pages — provider titles
                // may miss a required number or sentiment word for Rank Math.
                $canon_name = trim((string)($keyword_pack['primary'] ?? $focus_kw ?: $post->post_title));
                $seo_title = TemplateContent::build_default_model_seo_title($canon_name, '', $post_id);
                $meta_desc = TitleFixer::shorten((string)($claude_result['meta_description'] ?? ''), 160);

                $final_content = $insert_block
                    ? self::upsert_ai_block((string)$post->post_content, $generated_content)
                    : $generated_content;

                AssistedDraftEnrichmentService::persist_quality_score($post_id, $generated_content, $post, $focus_kw, $keyword_pack);

                wp_update_post(['ID' => $post_id, 'post_content' => $final_content]);

                if ($seo_title !== '') update_post_meta($post_id, 'rank_math_title', $seo_title);
                if ($meta_desc !== '') update_post_meta($post_id, 'rank_math_description', $meta_desc);
                if ($focus_kw !== '') {
                    if (!empty($keyword_pack) && class_exists('\\TMWSEO\\Engine\\Content\\RankMathMapper')) {
                        RankMathMapper::sync_to_rank_math($post_id, $keyword_pack, true);
                    } elseif (!get_post_meta($post_id, 'rank_math_focus_keyword', true)) {
                        update_post_meta($post_id, 'rank_math_focus_keyword', $focus_kw);
                    }
                    update_post_meta($post_id, '_tmwseo_keyword', $focus_kw);
                    AssistedDraftEnrichmentService::update_model_secondary_keywords_for_post($post, $focus_kw);
                }

                self::maybe_clear_rank_math_noindex($post);
                delete_post_meta($post_id, '_tmwseo_optimize_enqueued');
                update_post_meta($post_id, '_tmwseo_optimize_done', 'claude');

                Logs::info('content', '[TMW-CLAUDE] Claude content generated', [
                    'post_id'  => $post_id,
                    'strategy' => 'claude',
                ]);
                return;
            }

            // Claude failed — log it and fall through to OpenAI or template.
            Logs::warn('content', '[TMW-CLAUDE] Claude generation failed, falling back', [
                'post_id' => $post_id,
                'error'   => $claude_result['error'] ?? 'unknown',
            ]);
            $strategy = OpenAI::is_configured() ? 'openai' : 'template';
        }

        // Template generation is the default fallback (replaces the old "offline dry" placeholder).
        if ($strategy === 'template' || !OpenAI::is_configured()) {
            $focus_kw = '';
            if ($post->post_type === 'model' && !empty($keyword_pack['primary'])) {
                $focus_kw = (string)$keyword_pack['primary'];
            } else {
                $focus_kw = trim((string)get_post_meta($post_id, '_tmwseo_keyword', true));
                if ($focus_kw === '') $focus_kw = trim((string)$post->post_title);
            }
            $focus_kw = AssistedDraftEnrichmentService::normalize_focus_keyword_for_post($post, $focus_kw);

            if ($post->post_type === 'model') {
                $tpl = \TMWSEO\Engine\Content\TemplateContent::build_model($post, $keyword_pack);
                $generated_content = (string)$tpl['content'];
                $seo_title = TitleFixer::shorten((string)$tpl['seo_title'], 70);
                $meta_desc = TitleFixer::shorten((string)$tpl['meta_description'], 160);
            } else {
                // Generic template fallback.
                $seo_title = TitleFixer::shorten(TitleFixer::fix((string)$post->post_title), 70);
                $meta_desc = TitleFixer::shorten('Learn more about ' . $post->post_title . ' on ' . get_bloginfo('name') . '.', 160);
                $generated_content = '<h2>' . esc_html($post->post_title) . '</h2><p>Content template is not configured for this post type yet.</p>';
            }

            $final_content = $insert_block ? self::upsert_ai_block((string)$post->post_content, $generated_content) : $generated_content;
            AssistedDraftEnrichmentService::persist_quality_score($post_id, $generated_content, $post, $focus_kw, $keyword_pack);

            wp_update_post([
                'ID'           => $post_id,
                'post_content' => $final_content,
            ]);

            if ($seo_title !== '') update_post_meta($post_id, 'rank_math_title', $seo_title);
            if ($meta_desc !== '') update_post_meta($post_id, 'rank_math_description', $meta_desc);
            if ($focus_kw !== '') {
                // Patch 2: use centralized RankMathMapper (focus + 4 extras cap).
                if (!empty($keyword_pack) && class_exists('\\TMWSEO\\Engine\\Content\\RankMathMapper')) {
                    RankMathMapper::sync_to_rank_math($post_id, $keyword_pack, true);
                } elseif (!get_post_meta($post_id, 'rank_math_focus_keyword', true)) {
                    update_post_meta($post_id, 'rank_math_focus_keyword', $focus_kw);
                }
                update_post_meta($post_id, '_tmwseo_keyword', $focus_kw);
                AssistedDraftEnrichmentService::update_model_secondary_keywords_for_post($post, $focus_kw);
            }

            // Don't automatically remove noindex unless explicitly enabled.
            self::maybe_clear_rank_math_noindex($post);

            delete_post_meta($post_id, '_tmwseo_optimize_enqueued');
            update_post_meta($post_id, '_tmwseo_optimize_done', ($strategy === 'template') ? 'template' : 'template_fallback');

            Logs::info('content', 'Template content generated', [
                'post_id' => $post_id,
                'strategy' => $strategy,
                'openai_configured' => OpenAI::is_configured(),
            ]);

            return;
        }

        $context = (string)($payload['context'] ?? self::infer_context($post));
        $keyword = (string)($payload['keyword'] ?? get_post_meta($post_id, '_tmwseo_keyword', true));
        if ($post->post_type === 'model' && !empty($keyword_pack['primary'])) {
            $keyword = (string)$keyword_pack['primary'];
        }
        $secondary_keywords = [];
        if ($post->post_type === 'model') {
            $primary_keyword = AssistedDraftEnrichmentService::normalize_focus_keyword_for_post($post, $keyword);
            $secondary_keywords = (!empty($keyword_pack['additional']) && is_array($keyword_pack['additional']))
                ? array_slice(array_values(array_filter(array_map('strval', $keyword_pack['additional']))), 0, 4)
                : AssistedDraftEnrichmentService::build_model_secondary_keywords($primary_keyword);
        }

        $clean_title = TitleFixer::fix((string)$post->post_title);
        $clean_title_short = TitleFixer::shorten($clean_title, 70);

        $model = Settings::openai_model_for_quality();

        $length_hint = ($context === 'keyword_page' || $context === 'category_page') ? '500-800 words' : ($context === 'model' ? '1200-1501 words' : '150-350 words');

        $system = [
            'role' => 'system',
            'content' =>
                "You are a professional SEO copywriter for top-models.webcam.\n" .
                "Write informative, human-readable content about adult webcam / live video chat.\n" .
                "Keep language non-explicit and safe: do NOT describe graphic sexual acts.\n" .
                "Focus on user intent (features, safety, privacy, etiquette, what to expect).\n" .
                "Output STRICT JSON with keys: seo_title, meta_description, focus_keyword, intro_paragraphs, watch_section_paragraphs, about_section_paragraphs, fans_like_section_paragraphs, features_section_paragraphs, comparison_section_paragraphs, faq_items.\n" .
                "seo_title <= 65 characters. meta_description 145-160 characters.\n" .
                "Do not include h1 or raw section HTML architecture in any JSON value.\n" .
                "PROSE QUALITY RULES (non-negotiable):\n" .
                "- Never repeat the exact focus keyword more than twice in a single paragraph.\n" .
                "- Keep the exact model name natural; do not force pronouns as a density fix, and never rewrite usernames or literal keyword phrases.\n" .
                "- Do not begin more than one paragraph across ALL sections with 'Viewers who', 'People looking up', or 'Searches for/around'.\n" .
                "- faq_items answers must be 2-3 complete sentences each and should read like straightforward replies, not mini essays.\n" .
                "- Vary sentence length and opener across sections.\n" .
                "- Avoid signposting such as 'This guide covers', 'Here\'s what to know', or 'Let\'s dive in'.\n" .
                "- Avoid brochure phrasing, vague importance claims, and formulaic contrasts like 'it\'s not just X, it\'s Y'. Use direct sentences.\n" .
                "- Avoid the phrases 'official live profile' and 'trusted room links' entirely.\n" .
                "- Use 'official profile links' at most once across the entire output.\n"
        ];

        $user_content =
            "PAGE CONTEXT\n" .
            "- Post type: {$post->post_type}\n" .
            "- Context: {$context}\n" .
            "- Current title (cleaned): {$clean_title_short}\n" .
            ($keyword ? "- Primary keyword (must be used exactly): {$keyword}\n" : '') .
            (!empty($secondary_keywords) ? "- Secondary keywords (sprinkle naturally): " . implode(', ', $secondary_keywords) . "\n" : '') .
            (!empty($keyword_pack['longtail']) && is_array($keyword_pack['longtail']) ? "- Long-tail queries to cover: " . implode('; ', array_slice($keyword_pack['longtail'], 0, 6)) . "\n" : '') .
            "- Target length: {$length_hint}\n" .
            "\n" .
            "WRITE:\n" .
            "1) SEO title that matches the page and includes the keyword naturally.\n" .
            "2) Meta description with a clear value proposition.\n" .
            "3) One focus keyword (short).\n" .
            "4) Provide section paragraph arrays and faq_items (3-5 Q&As).\n";

        $is_model_page = ($post->post_type === 'model');

        if ($is_model_page) {
            $primary_keyword = AssistedDraftEnrichmentService::normalize_focus_keyword_for_post($post, $keyword !== '' ? $keyword : (string)$post->post_title);
            $user_content .= "\nMODEL PAGE TEMPLATE (required):\n" .
                "- Return ONLY structured JSON fields — no HTML headings, no raw HTML in values:\n" .
                "  intro_paragraphs (2-3 items), watch_section_paragraphs (1-2 items), about_section_paragraphs (2-3 items),\n" .
                "  fans_like_section_paragraphs (2-3 items), features_section_paragraphs (2-3 items),\n" .
                "  comparison_section_paragraphs (1-2 items), faq_items (4-5 objects with q and a keys).\n" .
                "- Ensure the primary keyword appears naturally in intro_paragraphs[0] and at least two other sections.\n" .
                "- Hard minimum word count across all prose sections: " . self::MODEL_MIN_WORDS . " words.\n" .
                "- Preferred target: 1200–1501 words — expand each section generously to reach this.\n" .
                "- Each section must contain at least 80 words.\n" .
                "- Use varied paragraph openers — never start two consecutive paragraphs the same way.\n" .
                "- Keep exact focus-keyword density between " . self::MODEL_MIN_KEYWORD_DENSITY . "% and " . self::MODEL_MAX_KEYWORD_DENSITY . "%.\n" .
                "- fans_like_section_paragraphs: describe what keeps viewers coming back — use varied sentence structures, not a repeated formula.\n" .
                "- Weave the four secondary keywords lightly and naturally; do not dump them as a list or repeat them mechanically.\n" .
                "- Use concrete observations about pace, chat style, scheduling, privacy, or room features instead of generic filler.\n" .
                "- faq_items: write natural questions real viewers would ask; answers must be 2-3 complete sentences.\n";
        }

        $user = [
            'role' => 'user',
            'content' => $user_content,
        ];

        $debug = (bool) Settings::get('debug_mode', false);
        if ($debug) { error_log('TMW run_optimize_job GENERATING CONTENT'); }
        $max_tokens = $is_model_page ? 4096 : 2200;
        $res = OpenAI::chat_json([$system, $user], $model, [
            'temperature' => 0.6,
            'max_tokens' => $max_tokens,
        ]);

        if (!$res['ok']) {
            Logs::error('content', 'OpenAI generation failed', ['post_id' => $post_id, 'error' => $res['error'] ?? '']);
            delete_post_meta($post_id, '_tmwseo_optimize_enqueued');
            if ($debug) { error_log('TMW run_optimize_job EARLY RETURN'); }
            return;
        }

        $j = $res['json'] ?? [];
        $seo_title = isset($j['seo_title']) ? (string)$j['seo_title'] : '';
        $meta_desc = isset($j['meta_description']) ? (string)$j['meta_description'] : '';
        $focus_kw  = isset($j['focus_keyword']) ? (string)$j['focus_keyword'] : '';
        $html      = (isset($j['content_html']) && is_string($j['content_html'])) ? $j['content_html'] : '';

        $seo_title = TitleFixer::shorten(trim($seo_title), 60);
        if ($is_model_page) {
            // Always replace with the canonical builder for model pages.
            // Provider titles may miss a required number or sentiment word.
            $fallback_name = trim((string)($keyword_pack['primary'] ?? $keyword ?: $post->post_title));
            $seo_title = TemplateContent::build_default_model_seo_title($fallback_name, '', $post_id);
        }
        $meta_desc = trim($meta_desc);
        // For model pages, focus keyword must be the model name.
        if ($is_model_page && !empty($keyword_pack['primary'])) {
            $focus_kw = (string)$keyword_pack['primary'];
        }
        $focus_kw  = trim($focus_kw);
        $focus_kw  = AssistedDraftEnrichmentService::normalize_focus_keyword_for_post($post, $focus_kw);

        if ($is_model_page) {
            $support_payload = TemplateContent::build_model_renderer_support_payload($post, $keyword_pack);
            $renderer_payload = array_merge($support_payload, self::extract_model_renderer_payload($j));
            $html = ModelPageRenderer::render((string)$post->post_title, $renderer_payload);
            $validated = self::enforce_model_content_constraints([$system, $user], $model, $max_tokens, $focus_kw, $html, $j, (string)$post->post_title, $support_payload);
            $html = $validated['html'];
            $focus_kw = $validated['focus_keyword'];
        }

        $html      = wp_kses_post(trim($html));
        $generated_content = $html;
        if ($debug) { error_log('TMW run_optimize_job CONTENT_LENGTH=' . strlen($generated_content)); }

        AssistedDraftEnrichmentService::persist_quality_score($post_id, $generated_content, $post, $focus_kw, $keyword_pack);

        if ($seo_title !== '') update_post_meta($post_id, 'rank_math_title', $seo_title);
        if ($meta_desc !== '') update_post_meta($post_id, 'rank_math_description', $meta_desc);
        if ($focus_kw !== '') {
            // Patch 2: use centralized RankMathMapper (focus + 4 extras cap).
            if (!empty($keyword_pack) && class_exists('\\TMWSEO\\Engine\\Content\\RankMathMapper')) {
                RankMathMapper::sync_to_rank_math($post_id, $keyword_pack, true);
            } elseif (!get_post_meta($post_id, 'rank_math_focus_keyword', true)) {
                update_post_meta($post_id, 'rank_math_focus_keyword', $focus_kw);
            }
            update_post_meta($post_id, '_tmwseo_keyword', $focus_kw);
            AssistedDraftEnrichmentService::update_model_secondary_keywords_for_post($post, $focus_kw);
        }

        // Update content via a dedicated marker block (optional).
        $new_content = $insert_block ? self::upsert_ai_block((string)$post->post_content, $html) : $html;

        // Only update post if content actually changed.
        if ($new_content !== (string)$post->post_content) {
            if ($debug) { error_log('TMW run_optimize_job UPDATING POST'); }
            wp_update_post([
                'ID' => $post_id,
                'post_content' => $new_content,
            ]);
            if ($debug) { error_log('TMW run_optimize_job UPDATE COMPLETE'); }
        }

        delete_post_meta($post_id, '_tmwseo_optimize_enqueued');
        update_post_meta($post_id, '_tmwseo_optimize_done', current_time('mysql'));

        self::maybe_clear_rank_math_noindex($post);

        Logs::info('content', 'Optimized', ['post_id' => $post_id, 'context' => $context, 'model' => $model]);
    }


    private static function is_manual_model_request(\WP_Post $post, array $payload): bool {
        if ($post->post_type !== 'model') {
            return false;
        }

        $trigger = sanitize_key((string)($payload['trigger'] ?? ''));
        $explicit = !empty($payload['explicit_generate']);

        return $trigger === 'manual' || $explicit;
    }

    /**
     * Manual model bootstrap for explicit Generate / Refresh clicks only.
     *
     * Safely hydrates missing keyword prerequisites before the content gate runs,
     * without weakening manual-only / no-auto-publish architecture.
     *
     * @param array<string,mixed> $keyword_pack
     * @return array<string,mixed>
     */
    private static function bootstrap_manual_model_generate(\WP_Post $post, array $keyword_pack): array {
        if ($post->post_type !== 'model') {
            return $keyword_pack;
        }

        if (class_exists(TemplateContent::class) && method_exists(TemplateContent::class, 'hydrate_model_keyword_pack')) {
            $keyword_pack = TemplateContent::hydrate_model_keyword_pack($post, $keyword_pack);
        }

        $primary = trim((string)($keyword_pack['primary'] ?? ''));
        if ($primary === '') {
            $primary = trim((string)get_post_meta($post->ID, '_tmwseo_keyword', true));
        }
        if ($primary === '') {
            $primary = trim((string)$post->post_title);
        }
        $primary = AssistedDraftEnrichmentService::normalize_focus_keyword_for_post($post, $primary);
        if ($primary !== '') {
            $keyword_pack['primary'] = $primary;
            update_post_meta($post->ID, '_tmwseo_keyword', $primary);
        }

        $additional = isset($keyword_pack['additional']) && is_array($keyword_pack['additional'])
            ? array_values(array_filter(array_map('strval', $keyword_pack['additional']), 'strlen'))
            : [];
        $longtail = isset($keyword_pack['longtail']) && is_array($keyword_pack['longtail'])
            ? array_values(array_filter(array_map('strval', $keyword_pack['longtail']), 'strlen'))
            : [];

        foreach (array_slice($additional, 0, 4) as $index => $keyword) {
            $meta_key = '_tmwseo_extra_focus_' . (string)($index + 1);
            if (trim((string)get_post_meta($post->ID, $meta_key, true)) === '') {
                update_post_meta($post->ID, $meta_key, $keyword);
            }
        }

        $confidence_raw = get_post_meta($post->ID, '_tmwseo_keyword_confidence', true);
        $confidence_val = is_numeric($confidence_raw) ? (float)$confidence_raw : 0.0;
        if ($confidence_val < 10.0) {
            $bootstrap_confidence = (!empty($longtail) || count($additional) >= 3) ? 72.0 : 55.0;
            update_post_meta($post->ID, '_tmwseo_keyword_confidence', $bootstrap_confidence);
        }

        if ($primary !== '') {
            if (class_exists('\TMWSEO\Engine\Content\RankMathMapper')) {
                RankMathMapper::sync_to_rank_math($post->ID, $keyword_pack, true);
            } else {
                update_post_meta($post->ID, 'rank_math_focus_keyword', $primary);
                if (!empty($additional)) {
                    update_post_meta($post->ID, 'rank_math_additional_keywords', implode(', ', array_slice($additional, 0, 10)));
                }
            }
            AssistedDraftEnrichmentService::update_model_secondary_keywords_for_post($post, $primary);
        }

        Logs::info('content', '[TMW-MODEL-BOOTSTRAP] Manual model prerequisites hydrated', [
            'post_id' => (int)$post->ID,
            'primary_keyword' => $primary,
            'additional_keywords' => count($additional),
            'longtail_keywords' => count($longtail),
            'confidence' => (float) get_post_meta($post->ID, '_tmwseo_keyword_confidence', true),
        ]);

        return $keyword_pack;
    }

    /**
     * @param array<string,mixed> $json
     * @return array<string,mixed>
     */
    private static function extract_model_renderer_payload(array $json): array {
        return [
            'focus_keyword' => (string)($json['focus_keyword'] ?? ''),
            'intro_paragraphs' => isset($json['intro_paragraphs']) && is_array($json['intro_paragraphs']) ? $json['intro_paragraphs'] : [],
            'watch_section_paragraphs' => isset($json['watch_section_paragraphs']) && is_array($json['watch_section_paragraphs']) ? $json['watch_section_paragraphs'] : [],
            'about_section_paragraphs' => isset($json['about_section_paragraphs']) && is_array($json['about_section_paragraphs']) ? $json['about_section_paragraphs'] : [],
            'fans_like_section_paragraphs' => isset($json['fans_like_section_paragraphs']) && is_array($json['fans_like_section_paragraphs']) ? $json['fans_like_section_paragraphs'] : [],
            'features_section_paragraphs' => isset($json['features_section_paragraphs']) && is_array($json['features_section_paragraphs']) ? $json['features_section_paragraphs'] : [],
            'comparison_section_paragraphs' => isset($json['comparison_section_paragraphs']) && is_array($json['comparison_section_paragraphs']) ? $json['comparison_section_paragraphs'] : [],
            'faq_items' => isset($json['faq_items']) && is_array($json['faq_items']) ? $json['faq_items'] : [],
        ];
    }

    /**
     * @param array<string,mixed> $model_json
     */
    private static function enforce_model_content_constraints(array $messages, string $model, int $max_tokens, string $focus_kw, string $html, array $model_json = [], string $model_name = '', array $support_payload = []): array {
        $focus_kw = trim($focus_kw);
        $attempts = 0;

        while ($attempts < 2) {
            $word_count = self::count_words($html);
            $density = self::keyword_density_percent($html, $focus_kw);

            if ($word_count >= self::MODEL_MIN_WORDS && $density >= self::MODEL_MIN_KEYWORD_DENSITY && $density <= self::MODEL_MAX_KEYWORD_DENSITY) {
                break;
            }

            $feedback = "Rewrite model sections only and return full JSON again while preserving SEO intent.\n" .
                "- Minimum words: " . self::MODEL_MIN_WORDS . " (current: {$word_count}).\n" .
                "- Expand sections with additional descriptive paragraphs.\n" .
                "- Keep exact focus keyword density between " . self::MODEL_MIN_KEYWORD_DENSITY . "% and " . self::MODEL_MAX_KEYWORD_DENSITY . "% (current: " . round($density, 2) . "%).\n" .
                "- Focus keyword must remain: {$focus_kw}.\n";

            $retry_messages = $messages;
            $retry_messages[] = [
                'role' => 'assistant',
                'content' => wp_json_encode([
                    'focus_keyword' => $focus_kw,
                    'intro_paragraphs' => $model_json['intro_paragraphs'] ?? [],
                    'watch_section_paragraphs' => $model_json['watch_section_paragraphs'] ?? [],
                    'about_section_paragraphs' => $model_json['about_section_paragraphs'] ?? [],
                    'fans_like_section_paragraphs' => $model_json['fans_like_section_paragraphs'] ?? [],
                    'features_section_paragraphs' => $model_json['features_section_paragraphs'] ?? [],
                    'comparison_section_paragraphs' => $model_json['comparison_section_paragraphs'] ?? [],
                    'faq_items' => $model_json['faq_items'] ?? [],
                ]),
            ];
            $retry_messages[] = [
                'role' => 'user',
                'content' => $feedback,
            ];
            $retry = OpenAI::chat_json($retry_messages, $model, [
                'temperature' => 0.5,
                'max_tokens' => $max_tokens,
            ]);

            if (!$retry['ok']) {
                break;
            }

            $json = $retry['json'] ?? [];
            $new_html = '';
            if (is_array($json)) {
                $model_json = $json;
                $new_html = ModelPageRenderer::render(
                    $model_name !== '' ? $model_name : $focus_kw,
                    array_merge($support_payload, self::extract_model_renderer_payload($model_json))
                );
            }
            $new_focus = isset($json['focus_keyword']) ? trim((string)$json['focus_keyword']) : '';

            if ($new_html !== '') {
                $html = $new_html;
            }
            if ($new_focus !== '') {
                $focus_kw = $new_focus;
            }

            $attempts++;
        }

        return [
            'html' => $html,
            'focus_keyword' => $focus_kw,
        ];
    }

    private static function count_words(string $html): int {
        $text = trim((string) wp_strip_all_tags($html));
        if ($text === '') return 0;

        preg_match_all('/\b[\p{L}\p{N}\']+\b/u', $text, $matches);
        return isset($matches[0]) && is_array($matches[0]) ? count($matches[0]) : 0;
    }

    private static function keyword_density_percent(string $html, string $keyword): float {
        $keyword = trim($keyword);
        $word_count = self::count_words($html);
        if ($keyword === '' || $word_count === 0) return 0.0;

        $text = mb_strtolower((string) wp_strip_all_tags($html), 'UTF-8');
        $needle = mb_strtolower($keyword, 'UTF-8');
        $pattern = '/\b' . preg_quote($needle, '/') . '\b/u';
        preg_match_all($pattern, $text, $matches);
        $occurrences = isset($matches[0]) && is_array($matches[0]) ? count($matches[0]) : 0;

        return ($occurrences / $word_count) * 100;
    }


    private static function maybe_clear_rank_math_noindex(\WP_Post $post): void {
        // We keep noindex by default until you explicitly enable auto-indexing.
        if ((int) Settings::get('auto_clear_rank_math_noindex', 0) !== 1) {
            return;
        }
        if ((string) get_post_meta($post->ID, '_tmwseo_ready_to_index', true) !== '1') {
            return;
        }
        if ($post->post_status !== 'publish') return;
        if (!in_array($post->post_type, ['model', 'tmw_category_page'], true)) return;
        if (get_post_meta($post->ID, '_tmwseo_generated', true)) return;

        delete_post_meta($post->ID, 'rank_math_robots');
    }

    private static function upsert_ai_block(string $content, string $html): string {
        $marker = "<!-- TMWSEO:AI -->";
        $html = trim($html);

        if ($html === '') return $content;

        if (strpos($content, $marker) !== false) {
            $parts = explode($marker, $content, 2);
            $before = rtrim($parts[0]);
            return $before . "\n" . $marker . "\n" . $html . "\n";
        }

        // Append at end if marker doesn't exist.
        $content = rtrim($content);
        if ($content !== '') $content .= "\n\n";
        return $content . $marker . "\n" . $html . "\n";
    }

    public static function get_publish_autopilot_hook_status(): array {
        $allowed = self::is_publish_autopilot_allowed();
        $migration_counts = class_exists('\TMWSEO\Engine\AutopilotMigrationRegistry')
            ? \TMWSEO\Engine\AutopilotMigrationRegistry::status_counts()
            : [];

        return [
            'phase' => 'C',
            'legacy_publish_autopilot_hooks' => $allowed ? 'ON' : 'OFF',
            'hard_fence' => self::PHASE_A_PUBLISH_AUTOPILOT_HARD_FENCE ? 'ENABLED' : 'DISABLED',
            'hook_registered' => has_action('transition_post_status', [__CLASS__, 'on_transition_post_status']) !== false ? 'yes' : 'no',
            'migration_required_to_enable' => 'yes',
            'phase_c_migrated_safely' => (string) ($migration_counts[\TMWSEO\Engine\AutopilotMigrationRegistry::STATUS_MIGRATED_SAFELY] ?? 0),
            'phase_c_still_fenced' => (string) ($migration_counts[\TMWSEO\Engine\AutopilotMigrationRegistry::STATUS_STILL_FENCED] ?? 0),
            'phase_c_disallowed' => (string) ($migration_counts[\TMWSEO\Engine\AutopilotMigrationRegistry::STATUS_PHASE_C_DISALLOWED] ?? 0),
        ];
    }
}
